export let responses = {
  0: { text: "It is certain" },
  1: { text: "It is decidedly so" },
  2: { text: "Without a doubt" },
  3: { text: " Yes definitely" },
  4: { text: "You may rely on it" },
  5: { text: "As I see it, yes" },
  6: { text: "Most likely" },
  7: { text: "Outlook good" },
  8: { text: "Yes" },
  9: { text: "Signs point to yes" },
  10: { text: "Reply hazy, try again", indecisive: true },
  11: { text: "Ask again later", indecisive: true },
  12: { text: "Better not tell you now", indecisive: true },
  13: { text: "Cannot predict now", indecisive: true },
  14: { text: "Concentrate and ask again", indecisive: true },
  15: { text: "Don't count on it" },
  16: { text: "My reply is no" },
  17: { text: "My sources say no" },
  18: { text: "Outlook not so good" },
  19: { text: "Very doubtful" },
};
